@echo off
REM build test.cpp with files generated by bin2cpp

:configure_v140
echo Configuring VC++ 2015...
if not exist "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" exit /b 1
call "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" x86_amd64 || exit /b 1

:build_src
echo.
echo Building test.cpp...
set OUTDIR=%~dp0build-dir
mkdir %OUTDIR% || exit /b 1
pushd %OUTDIR%
cl /nologo /DEBUG /EHsc /W4 %~dp0\test.cpp %~dp0\generated.cpp || exit /b 1
popd

:run_test
if not exist %OUTDIR%\test.exe exit /b 1
echo.
%OUTDIR%\test.exe || exit /b 1
del /q %OUTDIR%\*
rd /q %OUTDIR%

echo Success!
exit /b 0
